// AICMS Local Browser-Persisted Demo Initial Data
// Strictly browser-local demo state (namespace: aicms_demo_v1_state)

export const DEMO_STORAGE_KEY = 'aicms_demo_v1_state';
export const DEMO_ROLE_KEY = 'aicms_demo_v1_role';
export const DEMO_ONBOARDING_KEY = 'aicms_demo_v1_onboarding';

export const INITIAL_DEMO_DATA = {
  clinic: {
    name: 'Sunrise Multispeciality Clinic',
    ownerName: 'Dr. Priya Sharma',
    tagline: 'Precision Care. Human Touch.',
    branches: ['Main Centre (MG Road)', 'Indiranagar Care Hub'],
    address: '42, 100 Feet Road, Indiranagar, Bengaluru, KA 560038',
    phone: '+91 80 4123 4567',
    email: 'contact@sunriseclinic.demo',
    plan: 'AI Enterprise Clinic Suite',
    currency: 'INR',
  },
  doctors: [
    {
      id: 'doc-1',
      name: 'Dr. Priya Sharma',
      specialization: 'General Medicine',
      experience: '12 Years',
      phone: '+91 98765 43210',
      email: 'dr.priya@sunriseclinic.demo',
      avatar: 'PS',
      status: 'Active',
      fee: 500,
      todaySlots: ['09:30 AM', '10:00 AM', '11:00 AM', '04:30 PM', '05:30 PM'],
    },
    {
      id: 'doc-2',
      name: 'Dr. Amit Verma',
      specialization: 'Cardiology',
      experience: '14 Years',
      phone: '+91 98765 43211',
      email: 'dr.amit@sunriseclinic.demo',
      avatar: 'AV',
      status: 'Active',
      fee: 800,
      todaySlots: ['10:30 AM', '11:30 AM', '02:30 PM', '04:00 PM'],
    },
    {
      id: 'doc-3',
      name: 'Dr. Neha Gupta',
      specialization: 'Dental',
      experience: '9 Years',
      phone: '+91 98765 43212',
      email: 'dr.neha@sunriseclinic.demo',
      avatar: 'NG',
      status: 'Active',
      fee: 600,
      todaySlots: ['11:00 AM', '12:30 PM', '03:00 PM', '05:00 PM'],
    },
    {
      id: 'doc-4',
      name: 'Dr. Rajesh Iyer',
      specialization: 'Ophthalmology',
      experience: '15 Years',
      phone: '+91 98765 43213',
      email: 'dr.rajesh@sunriseclinic.demo',
      avatar: 'RI',
      status: 'On Leave',
      fee: 750,
      todaySlots: [],
    },
  ],
  staff: [
    {
      id: 'st-1',
      name: 'Kavita Menon',
      role: 'Reception Desk Lead',
      department: 'Front Desk',
      shift: 'Morning (8:00 AM - 4:00 PM)',
      status: 'Active',
    },
    {
      id: 'st-2',
      name: 'Suresh Patil',
      role: 'Chief Pharmacist',
      department: 'Pharmacy',
      shift: 'Full Day (9:00 AM - 6:00 PM)',
      status: 'Active',
    },
    {
      id: 'st-3',
      name: 'Divya Nair',
      role: 'Senior Lab Technician',
      department: 'Diagnostic Laboratory',
      shift: 'Morning (7:30 AM - 3:30 PM)',
      status: 'Active',
    },
  ],
  patients: [
    {
      id: 'pat-1',
      name: 'Ramesh Kumar',
      age: 42,
      gender: 'Male',
      phone: '+91 98111 22334',
      bloodGroup: 'B+',
      vitals: { bp: '126/82', pulse: '74 bpm', spo2: '99%', temp: '98.4°F', weight: '74 kg' },
      history: 'Routine hypertension follow-up. Seasonal allergic rhinitis.',
      lastVisit: 'Today',
    },
    {
      id: 'pat-2',
      name: 'Anita Patel',
      age: 36,
      gender: 'Female',
      phone: '+91 98222 33445',
      bloodGroup: 'O+',
      vitals: { bp: '118/76', pulse: '72 bpm', spo2: '98%', temp: '98.6°F', weight: '60 kg' },
      history: 'Cardiology screening and preventative lipid evaluation.',
      lastVisit: 'Today',
    },
    {
      id: 'pat-3',
      name: 'Rahul Sharma',
      age: 29,
      gender: 'Male',
      phone: '+91 98333 44556',
      bloodGroup: 'A+',
      vitals: { bp: '120/80', pulse: '70 bpm', spo2: '99%', temp: '98.2°F', weight: '68 kg' },
      history: 'Dental scaling and routine molar checkup.',
      lastVisit: 'Today',
    },
    {
      id: 'pat-4',
      name: 'Sunita Verma',
      age: 48,
      gender: 'Female',
      phone: '+91 98444 55667',
      bloodGroup: 'AB+',
      vitals: { bp: '134/86', pulse: '78 bpm', spo2: '97%', temp: '98.8°F', weight: '71 kg' },
      history: 'Type 2 Diabetes review with fasting blood sugar assessment.',
      lastVisit: 'Yesterday',
    },
  ],
  appointments: [
    {
      id: 'apt-101',
      token: 'T-01',
      patientId: 'pat-1',
      patientName: 'Ramesh Kumar',
      doctorId: 'doc-1',
      doctorName: 'Dr. Priya Sharma',
      specialty: 'General Medicine',
      time: '10:00 AM',
      date: 'Today',
      type: 'Routine Consultation',
      reason: 'General checkup & mild allergy',
      status: 'CHECKED_IN', // SCHEDULED | CHECKED_IN | IN_CONSULTATION | COMPLETED
      fee: 500,
    },
    {
      id: 'apt-102',
      token: 'T-02',
      patientId: 'pat-2',
      patientName: 'Anita Patel',
      doctorId: 'doc-2',
      doctorName: 'Dr. Amit Verma',
      specialty: 'Cardiology',
      time: '10:30 AM',
      date: 'Today',
      type: 'Cardiac Assessment',
      reason: 'Preventive ECG & Lipid check',
      status: 'SCHEDULED',
      fee: 800,
    },
    {
      id: 'apt-103',
      token: 'T-03',
      patientId: 'pat-3',
      patientName: 'Rahul Sharma',
      doctorId: 'doc-3',
      doctorName: 'Dr. Neha Gupta',
      specialty: 'Dental',
      time: '11:00 AM',
      date: 'Today',
      type: 'Dental Checkup',
      reason: 'Tooth sensitivity & scaling',
      status: 'SCHEDULED',
      fee: 600,
    },
    {
      id: 'apt-104',
      token: 'T-04',
      patientId: 'pat-4',
      patientName: 'Sunita Verma',
      doctorId: 'doc-1',
      doctorName: 'Dr. Priya Sharma',
      specialty: 'General Medicine',
      time: '11:45 AM',
      date: 'Today',
      type: 'Diabetic Review',
      reason: 'HbA1c & Fasting sugar consult',
      status: 'COMPLETED',
      fee: 500,
    },
  ],
  prescriptions: [
    {
      id: 'rx-201',
      patientId: 'pat-1',
      patientName: 'Ramesh Kumar',
      doctorName: 'Dr. Priya Sharma',
      date: 'Today',
      diagnosis: 'Mild Seasonal Allergic Rhinitis',
      notes: 'Steam inhalation twice daily. Drink warm water and avoid dust exposure.',
      medicines: [
        { name: 'Cetirizine 10mg', dosage: '1 Tab', frequency: 'Once daily (Night)', duration: '5 Days', instruction: 'After food' },
        { name: 'Paracetamol 500mg', dosage: '1 Tab', frequency: 'Twice daily', duration: '3 Days', instruction: 'As needed for fever/headache' },
      ],
      labRecommendations: ['Complete Blood Count (CBC)'],
    },
    {
      id: 'rx-202',
      patientId: 'pat-4',
      patientName: 'Sunita Verma',
      doctorName: 'Dr. Priya Sharma',
      date: 'Yesterday',
      diagnosis: 'Type 2 Diabetes Mellitus — Under Control',
      notes: 'Maintain 30 min brisk walking. Continue low glycemic diet.',
      medicines: [
        { name: 'Metformin 500mg (SR)', dosage: '1 Tab', frequency: 'Twice daily', duration: '30 Days', instruction: 'With breakfast & dinner' },
        { name: 'Vitamin D3 60K', dosage: '1 Capsule', frequency: 'Once weekly', duration: '8 Weeks', instruction: 'After milk' },
      ],
      labRecommendations: ['HbA1c Glycated Hemoglobin', 'Lipid Profile'],
    },
  ],
  labOrders: [
    {
      id: 'lab-301',
      patientId: 'pat-1',
      patientName: 'Ramesh Kumar',
      testName: 'Complete Blood Count (CBC)',
      orderedBy: 'Dr. Priya Sharma',
      date: 'Today',
      price: 350,
      status: 'Completed', // Pending | Processing | Completed
      sampleType: 'Whole Blood (EDTA)',
      resultSummary: 'Hb: 14.6 g/dL, Total WBC: 7,200/mcL, Platelets: 2.8 Lakhs. Normal parameters.',
      qrVerified: true,
    },
    {
      id: 'lab-302',
      patientId: 'pat-4',
      patientName: 'Sunita Verma',
      testName: 'HbA1c Glycated Hemoglobin',
      orderedBy: 'Dr. Priya Sharma',
      date: 'Yesterday',
      price: 550,
      status: 'Completed',
      sampleType: 'Whole Blood (EDTA)',
      resultSummary: 'HbA1c: 6.7% (Target < 7.0%). Well-managed glycemic control.',
      qrVerified: true,
    },
    {
      id: 'lab-303',
      patientId: 'pat-2',
      patientName: 'Anita Patel',
      testName: 'Lipid Profile (Serum)',
      orderedBy: 'Dr. Amit Verma',
      date: 'Today',
      price: 750,
      status: 'Processing',
      sampleType: 'Serum (SST)',
      resultSummary: 'Sample in auto-analyzer queue. Triglycerides and HDL analysis in progress.',
      qrVerified: false,
    },
    {
      id: 'lab-304',
      patientId: 'pat-3',
      patientName: 'Rahul Sharma',
      testName: 'Liver Function Test (LFT)',
      orderedBy: 'Dr. Priya Sharma',
      date: 'Today',
      price: 600,
      status: 'Pending',
      sampleType: 'Serum (SST)',
      resultSummary: 'Sample accessioned at diagnostic desk.',
      qrVerified: false,
    },
  ],
  bills: [
    {
      id: 'inv-401',
      invoiceNumber: 'INV-2026-101',
      patientId: 'pat-1',
      patientName: 'Ramesh Kumar',
      doctorName: 'Dr. Priya Sharma',
      services: ['Consultation (General Medicine)', 'CBC Blood Test', 'Paracetamol 500mg'],
      subtotal: 900,
      discount: 50,
      amount: 850,
      date: 'Today',
      status: 'PAID', // PAID | PENDING
      mode: 'UPI (Instant)',
    },
    {
      id: 'inv-402',
      invoiceNumber: 'INV-2026-102',
      patientId: 'pat-2',
      patientName: 'Anita Patel',
      doctorName: 'Dr. Amit Verma',
      services: ['Cardiology Consultation', 'Lipid Profile Test'],
      subtotal: 1550,
      discount: 0,
      amount: 1550,
      date: 'Today',
      status: 'PENDING',
      mode: 'Pending at Counter',
    },
    {
      id: 'inv-403',
      invoiceNumber: 'INV-2026-103',
      patientId: 'pat-3',
      patientName: 'Rahul Sharma',
      doctorName: 'Dr. Neha Gupta',
      services: ['Dental Consultation', 'Molar Examination'],
      subtotal: 600,
      discount: 0,
      amount: 600,
      date: 'Today',
      status: 'PAID',
      mode: 'Cash',
    },
    {
      id: 'inv-404',
      invoiceNumber: 'INV-2026-104',
      patientId: 'pat-4',
      patientName: 'Sunita Verma',
      doctorName: 'Dr. Priya Sharma',
      services: ['Diabetic Follow-up', 'HbA1c Test', 'Metformin 500mg'],
      subtotal: 1200,
      discount: 100,
      amount: 1100,
      date: 'Yesterday',
      status: 'PAID',
      mode: 'Card (POS)',
    },
  ],
  medicines: [
    {
      id: 'med-1',
      name: 'Paracetamol 500mg',
      batch: 'PCM001',
      category: 'Analgesic',
      expiry: '12/2026',
      stock: 120,
      minStock: 50,
      unitPrice: 3.5,
      status: 'In Stock',
    },
    {
      id: 'med-2',
      name: 'Amoxicillin 250mg',
      batch: 'AMX002',
      category: 'Antibiotic',
      expiry: '03/2026',
      stock: 18,
      minStock: 30,
      unitPrice: 8.0,
      status: 'Low Stock',
    },
    {
      id: 'med-3',
      name: 'Vitamin D3 60K',
      batch: 'VIT003',
      category: 'Supplements',
      expiry: '09/2026',
      stock: 45,
      minStock: 25,
      unitPrice: 45.0,
      status: 'In Stock',
    },
    {
      id: 'med-4',
      name: 'Pantoprazole 40mg',
      batch: 'PAN004',
      category: 'Antacid',
      expiry: '07/2026',
      stock: 80,
      minStock: 40,
      unitPrice: 6.5,
      status: 'In Stock',
    },
    {
      id: 'med-5',
      name: 'Cetirizine 10mg',
      batch: 'CET005',
      category: 'Antihistamine',
      expiry: '08/2026',
      stock: 110,
      minStock: 50,
      unitPrice: 4.0,
      status: 'In Stock',
    },
    {
      id: 'med-6',
      name: 'Metformin 500mg (SR)',
      batch: 'MET006',
      category: 'Antidiabetic',
      expiry: '11/2026',
      stock: 95,
      minStock: 40,
      unitPrice: 5.5,
      status: 'In Stock',
    },
  ],
  notifications: [
    { id: 'notif-1', title: 'New Appointment', message: 'Ramesh Kumar booked with Dr. Priya Sharma', time: '10m ago', read: false },
    { id: 'notif-2', title: 'Lab Report Verified', message: 'CBC report for Ramesh Kumar released with QR code', time: '25m ago', read: false },
    { id: 'notif-3', title: 'Payment Received', message: '₹850 settled via UPI for INV-2026-101', time: '40m ago', read: true },
  ],
};
