// AICMS Local Browser-Persisted Demo Initial Data
export const INITIAL_DEMO_DATA = {
  clinic: {
    name: 'Apex Multi-Speciality Clinic',
    tagline: 'Care That Empowers',
    branches: ['Main Branch (Indiranagar)', 'South Branch (Koramangala)'],
    address: '100 Feet Road, Indiranagar, Bengaluru',
    phone: '+91 80 4123 4567',
    plan: 'AI Professional Clinic',
  },
  doctors: [
    {
      id: 'doc-1',
      name: 'Dr. Priya Sharma',
      specialization: 'General Medicine & Diabetology',
      experience: '12 Years',
      phone: '+91 98765 43210',
      email: 'dr.priya@apexhospital.in',
      avatar: 'PS',
      status: 'Available',
      fee: 600,
      todaySlots: ['09:30 AM', '10:15 AM', '11:00 AM', '12:00 PM', '04:30 PM', '05:30 PM'],
    },
    {
      id: 'doc-2',
      name: 'Dr. Amit Verma',
      specialization: 'Dental Surgeon & Orthodontics',
      experience: '8 Years',
      phone: '+91 98765 43211',
      email: 'dr.amit@apexhospital.in',
      avatar: 'AV',
      status: 'Available',
      fee: 800,
      todaySlots: ['10:00 AM', '11:30 AM', '02:30 PM', '04:00 PM'],
    },
    {
      id: 'doc-3',
      name: 'Dr. Neha Kapoor',
      specialization: 'Physiotherapy & Sports Rehab',
      experience: '10 Years',
      phone: '+91 98765 43212',
      email: 'dr.neha@apexhospital.in',
      avatar: 'NK',
      status: 'On Leave',
      fee: 700,
      todaySlots: [],
    },
    {
      id: 'doc-4',
      name: 'Dr. Rajesh Iyer',
      specialization: 'Ophthalmology & Eye Surgeon',
      experience: '15 Years',
      phone: '+91 98765 43213',
      email: 'dr.rajesh@apexhospital.in',
      avatar: 'RI',
      status: 'Available',
      fee: 900,
      todaySlots: ['11:00 AM', '03:00 PM', '05:00 PM'],
    },
  ],
  staff: [
    {
      id: 'st-1',
      name: 'Kavita Menon',
      role: 'Head Receptionist',
      department: 'Front Desk',
      shift: 'Morning (8 AM - 4 PM)',
      status: 'Active',
    },
    {
      id: 'st-2',
      name: 'Suresh Patil',
      role: 'Chief Pharmacist',
      department: 'Pharmacy',
      shift: 'Full Day (9 AM - 6 PM)',
      status: 'Active',
    },
    {
      id: 'st-3',
      name: 'Divya Nair',
      role: 'Lab Technician',
      department: 'Pathology Lab',
      shift: 'Morning (7 AM - 3 PM)',
      status: 'Active',
    },
    {
      id: 'st-4',
      name: 'Rahul Sen',
      role: 'Billing Executive',
      department: 'Accounts',
      shift: 'General (10 AM - 7 PM)',
      status: 'Active',
    },
  ],
  patients: [
    {
      id: 'pat-1',
      name: 'Rohan Mehta',
      age: 34,
      gender: 'Male',
      phone: '+91 98111 22334',
      bloodGroup: 'B+',
      vitals: { bp: '124/82', pulse: '76', spo2: '99%', temp: '98.4°F', weight: '72 kg' },
      history: 'Mild hypertension diagnosed in 2024. Occasional seasonal allergies.',
    },
    {
      id: 'pat-2',
      name: 'Ananya Singh',
      age: 28,
      gender: 'Female',
      phone: '+91 98222 33445',
      bloodGroup: 'O+',
      vitals: { bp: '118/78', pulse: '72', spo2: '98%', temp: '98.6°F', weight: '58 kg' },
      history: 'Routine health checkup. Pre-dental assessment for scaling.',
    },
    {
      id: 'pat-3',
      name: 'Rajesh Kumar',
      age: 52,
      gender: 'Male',
      phone: '+91 98333 44556',
      bloodGroup: 'A+',
      vitals: { bp: '136/88', pulse: '80', spo2: '97%', temp: '99.1°F', weight: '81 kg' },
      history: 'Type 2 Diabetes since 6 years. Under ongoing metformin regimen.',
    },
    {
      id: 'pat-4',
      name: 'Priya Patel',
      age: 41,
      gender: 'Female',
      phone: '+91 98444 55667',
      bloodGroup: 'AB+',
      vitals: { bp: '120/80', pulse: '74', spo2: '99%', temp: '98.2°F', weight: '64 kg' },
      history: 'Lower back stiffness post sedentary desk hours. Eye strain follow-up.',
    },
    {
      id: 'pat-5',
      name: 'Vikram Seth',
      age: 23,
      gender: 'Male',
      phone: '+91 98555 66778',
      bloodGroup: 'O-',
      vitals: { bp: '115/75', pulse: '68', spo2: '100%', temp: '98.4°F', weight: '66 kg' },
      history: 'Sports injury consult for ankle sprain rehabilitation.',
    },
  ],
  appointments: [
    {
      id: 'apt-101',
      patientId: 'pat-1',
      patientName: 'Rohan Mehta',
      doctorId: 'doc-1',
      doctorName: 'Dr. Priya Sharma',
      specialty: 'General Medicine',
      time: '10:30 AM',
      date: 'Today',
      type: 'Follow-up Consultation',
      reason: 'Blood pressure & seasonal allergy check',
      status: 'CHECKED_IN', // SCHEDULED | CHECKED_IN | IN_CONSULTATION | COMPLETED
      token: 'A-01',
    },
    {
      id: 'apt-102',
      patientId: 'pat-2',
      patientName: 'Ananya Singh',
      doctorId: 'doc-2',
      doctorName: 'Dr. Amit Verma',
      specialty: 'Dental Surgeon',
      time: '11:15 AM',
      date: 'Today',
      type: 'Dental Checkup',
      reason: 'Routine tooth cleaning & sensitivity',
      status: 'SCHEDULED',
      token: 'A-02',
    },
    {
      id: 'apt-103',
      patientId: 'pat-3',
      patientName: 'Rajesh Kumar',
      doctorId: 'doc-1',
      doctorName: 'Dr. Priya Sharma',
      specialty: 'General Medicine',
      time: '12:00 PM',
      date: 'Today',
      type: 'Diabetic Review',
      reason: 'HbA1c test review & dose adjustment',
      status: 'WAITING',
      token: 'A-03',
    },
    {
      id: 'apt-104',
      patientId: 'pat-4',
      patientName: 'Priya Patel',
      doctorId: 'doc-4',
      doctorName: 'Dr. Rajesh Iyer',
      specialty: 'Ophthalmology',
      time: '03:30 PM',
      date: 'Today',
      type: 'Vision Assessment',
      reason: 'Computer vision syndrome check',
      status: 'SCHEDULED',
      token: 'A-04',
    },
    {
      id: 'apt-105',
      patientId: 'pat-5',
      patientName: 'Vikram Seth',
      doctorId: 'doc-1',
      doctorName: 'Dr. Priya Sharma',
      specialty: 'General Medicine',
      time: '09:00 AM',
      date: 'Today',
      type: 'OPD Consult',
      reason: 'Mild fever & throat ache',
      status: 'COMPLETED',
      token: 'A-00',
    },
  ],
  prescriptions: [
    {
      id: 'rx-201',
      patientId: 'pat-1',
      patientName: 'Rohan Mehta',
      doctorName: 'Dr. Priya Sharma',
      date: '08 Oct 2026',
      diagnosis: 'Mild Sinusitis & Seasonal Rhinitis',
      notes: 'Advised warm hydration and avoidance of cold drafts. Return if fever persists.',
      medicines: [
        { name: 'Cetirizine 10mg', dosage: '1 Tab', frequency: 'Once daily (Night)', duration: '5 Days', instruction: 'After food' },
        { name: 'Paracetamol 500mg', dosage: '1 Tab', frequency: 'Twice daily', duration: '3 Days', instruction: 'As needed for headache' },
        { name: 'Saline Nasal Spray', dosage: '2 Puffs', frequency: 'Thrice daily', duration: '5 Days', instruction: 'Both nostrils' },
      ],
      labRecommendations: ['Complete Blood Count (CBC)'],
    },
    {
      id: 'rx-202',
      patientId: 'pat-3',
      patientName: 'Rajesh Kumar',
      doctorName: 'Dr. Priya Sharma',
      date: '06 Oct 2026',
      diagnosis: 'Type 2 Diabetes Mellitus (Stable)',
      notes: 'Continue 30 min morning walks. Moderate carbohydrate intake.',
      medicines: [
        { name: 'Metformin 500mg (SR)', dosage: '1 Tab', frequency: 'Twice daily', duration: '30 Days', instruction: 'With meals' },
        { name: 'Vitamin B12 Complex', dosage: '1 Cap', frequency: 'Once daily', duration: '30 Days', instruction: 'Morning' },
      ],
      labRecommendations: ['HbA1c Glycated Hemoglobin', 'Lipid Profile (Serum)'],
    },
  ],
  labOrders: [
    {
      id: 'lab-301',
      patientId: 'pat-1',
      patientName: 'Rohan Mehta',
      testName: 'Complete Blood Count (CBC)',
      orderedBy: 'Dr. Priya Sharma',
      date: 'Today',
      status: 'Verified',
      sampleType: 'Whole Blood (EDTA)',
      resultSummary: 'Hb: 14.8 g/dL, WBC: 7,400 /mcL, Platelets: 2.6 Lakhs. Normal parameters.',
      qrVerified: true,
    },
    {
      id: 'lab-302',
      patientId: 'pat-3',
      patientName: 'Rajesh Kumar',
      testName: 'HbA1c Glycated Hemoglobin',
      orderedBy: 'Dr. Priya Sharma',
      date: '06 Oct 2026',
      status: 'Verified',
      sampleType: 'Whole Blood (EDTA)',
      resultSummary: 'HbA1c: 6.8% (Target < 7.0%). Well controlled glycemic level.',
      qrVerified: true,
    },
    {
      id: 'lab-303',
      patientId: 'pat-4',
      patientName: 'Priya Patel',
      testName: 'Lipid Profile (Serum)',
      orderedBy: 'Dr. Priya Sharma',
      date: 'Today',
      status: 'In Progress',
      sampleType: 'Serum (SST)',
      resultSummary: 'Sample in auto-analyzer queue.',
      qrVerified: false,
    },
  ],
  bills: [
    {
      id: 'inv-401',
      invoiceNumber: 'INV-2026-901',
      patientId: 'pat-1',
      patientName: 'Rohan Mehta',
      services: ['Doctor Consultation (Dr. Priya Sharma)', 'CBC Blood Test'],
      amount: 1250,
      date: 'Today',
      status: 'PAID', // PAID | PENDING
      mode: 'UPI (GPay)',
    },
    {
      id: 'inv-402',
      invoiceNumber: 'INV-2026-902',
      patientId: 'pat-2',
      patientName: 'Ananya Singh',
      services: ['Dental Consultation (Dr. Amit Verma)', 'Digital X-Ray IOPA'],
      amount: 1400,
      date: 'Today',
      status: 'PENDING',
      mode: 'Pay at Desk / QR',
    },
    {
      id: 'inv-403',
      invoiceNumber: 'INV-2026-903',
      patientId: 'pat-3',
      patientName: 'Rajesh Kumar',
      services: ['Diabetic Follow-up Consult', 'HbA1c Test'],
      amount: 1100,
      date: '06 Oct 2026',
      status: 'PAID',
      mode: 'Credit Card',
    },
    {
      id: 'inv-404',
      invoiceNumber: 'INV-2026-904',
      patientId: 'pat-4',
      patientName: 'Priya Patel',
      services: ['Ophthalmology Exam', 'Lipid Profile'],
      amount: 1550,
      date: 'Today',
      status: 'PENDING',
      mode: 'Pending Collection',
    },
    {
      id: 'inv-405',
      invoiceNumber: 'INV-2026-905',
      patientId: 'pat-5',
      patientName: 'Vikram Seth',
      services: ['General OPD Consult', 'Pharmacy Medicines'],
      amount: 890,
      date: 'Today',
      status: 'PAID',
      mode: 'Cash',
    },
  ],
  medicines: [
    {
      id: 'med-1',
      name: 'Paracetamol 500mg',
      batch: 'B001',
      expiry: '12/2026',
      stock: 48,
      unitPrice: 3.5,
      category: 'Analgesic',
    },
    {
      id: 'med-2',
      name: 'Amoxicillin 250mg',
      batch: 'B002',
      expiry: '03/2026',
      stock: 24,
      unitPrice: 8.0,
      category: 'Antibiotic',
    },
    {
      id: 'med-3',
      name: 'Cetirizine 10mg',
      batch: 'B003',
      expiry: '08/2026',
      stock: 65,
      unitPrice: 4.0,
      category: 'Antihistamine',
    },
    {
      id: 'med-4',
      name: 'Metformin 500mg (SR)',
      batch: 'B004',
      expiry: '11/2026',
      stock: 90,
      unitPrice: 5.5,
      category: 'Antidiabetic',
    },
    {
      id: 'med-5',
      name: 'Vitamin D3 60K (Nano Drops)',
      batch: 'B005',
      expiry: '09/2026',
      stock: 32,
      unitPrice: 45.0,
      category: 'Supplements',
    },
  ],
  notifications: [
    { id: 'notif-1', title: 'New Appointment', message: 'Rohan Mehta booked with Dr. Priya Sharma', time: '10m ago', read: false },
    { id: 'notif-2', title: 'Lab Report Verified', message: 'CBC report for Rohan Mehta released with QR code', time: '25m ago', read: false },
    { id: 'notif-3', title: 'Payment Received', message: '₹1,250 settled via UPI for INV-2026-901', time: '40m ago', read: true },
  ],
};
