const APPOINTMENT_STATUSES = {
  BOOKED: 'booked',
  CONFIRMED: 'confirmed',
  CHECKED_IN: 'checked_in',
  IN_CONSULTATION: 'in_consultation',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
  NO_SHOW: 'no_show',
  RESCHEDULED: 'rescheduled'
};

const ACTIVE_APPOINTMENT_STATUSES = [
  APPOINTMENT_STATUSES.BOOKED,
  APPOINTMENT_STATUSES.CONFIRMED,
  APPOINTMENT_STATUSES.CHECKED_IN,
  APPOINTMENT_STATUSES.IN_CONSULTATION
];

const APPOINTMENT_STATUS_TRANSITIONS = {
  [APPOINTMENT_STATUSES.BOOKED]: [
    APPOINTMENT_STATUSES.CONFIRMED,
    APPOINTMENT_STATUSES.CANCELLED,
    APPOINTMENT_STATUSES.NO_SHOW,
    APPOINTMENT_STATUSES.RESCHEDULED
  ],
  [APPOINTMENT_STATUSES.CONFIRMED]: [
    APPOINTMENT_STATUSES.CHECKED_IN,
    APPOINTMENT_STATUSES.CANCELLED,
    APPOINTMENT_STATUSES.NO_SHOW,
    APPOINTMENT_STATUSES.RESCHEDULED
  ],
  [APPOINTMENT_STATUSES.CHECKED_IN]: [APPOINTMENT_STATUSES.IN_CONSULTATION],
  [APPOINTMENT_STATUSES.IN_CONSULTATION]: [APPOINTMENT_STATUSES.COMPLETED],
  [APPOINTMENT_STATUSES.COMPLETED]: [],
  [APPOINTMENT_STATUSES.CANCELLED]: [],
  [APPOINTMENT_STATUSES.NO_SHOW]: [],
  [APPOINTMENT_STATUSES.RESCHEDULED]: []
};

const DOCTOR_ALLOWED_STATUS_UPDATES = [
  APPOINTMENT_STATUSES.CHECKED_IN,
  APPOINTMENT_STATUSES.IN_CONSULTATION,
  APPOINTMENT_STATUSES.COMPLETED
];

module.exports = {
  APPOINTMENT_STATUSES,
  ACTIVE_APPOINTMENT_STATUSES,
  APPOINTMENT_STATUS_TRANSITIONS,
  DOCTOR_ALLOWED_STATUS_UPDATES
};
