const APPOINTMENT_STATUSES = {
  BOOKED: 'booked',
  CONFIRMED: 'confirmed',
  CHECKED_IN: 'checked_in',
  LATE_CHECK_IN: 'late_check_in',
  CALLED: 'called',
  IN_CONSULTATION: 'in_consultation',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
  NO_SHOW: 'no_show',
  RESCHEDULED: 'rescheduled',
  PATIENT_CANCELLED: 'patient_cancelled',
  CLINIC_CANCELLED: 'clinic_cancelled',
  PATIENT_RESCHEDULED: 'patient_rescheduled',
  CLINIC_RESCHEDULED: 'clinic_rescheduled'
};

const ACTIVE_APPOINTMENT_STATUSES = [
  APPOINTMENT_STATUSES.BOOKED,
  APPOINTMENT_STATUSES.CONFIRMED,
  APPOINTMENT_STATUSES.CHECKED_IN,
  APPOINTMENT_STATUSES.LATE_CHECK_IN,
  APPOINTMENT_STATUSES.CALLED,
  APPOINTMENT_STATUSES.IN_CONSULTATION
];

const APPOINTMENT_STATUS_TRANSITIONS = {
  [APPOINTMENT_STATUSES.BOOKED]: [
    APPOINTMENT_STATUSES.CONFIRMED,
    APPOINTMENT_STATUSES.CANCELLED,
    APPOINTMENT_STATUSES.PATIENT_CANCELLED,
    APPOINTMENT_STATUSES.CLINIC_CANCELLED,
    APPOINTMENT_STATUSES.NO_SHOW,
    APPOINTMENT_STATUSES.RESCHEDULED,
    APPOINTMENT_STATUSES.PATIENT_RESCHEDULED,
    APPOINTMENT_STATUSES.CLINIC_RESCHEDULED
  ],
  [APPOINTMENT_STATUSES.CONFIRMED]: [
    APPOINTMENT_STATUSES.CHECKED_IN,
    APPOINTMENT_STATUSES.LATE_CHECK_IN,
    APPOINTMENT_STATUSES.CANCELLED,
    APPOINTMENT_STATUSES.PATIENT_CANCELLED,
    APPOINTMENT_STATUSES.CLINIC_CANCELLED,
    APPOINTMENT_STATUSES.NO_SHOW,
    APPOINTMENT_STATUSES.RESCHEDULED,
    APPOINTMENT_STATUSES.PATIENT_RESCHEDULED,
    APPOINTMENT_STATUSES.CLINIC_RESCHEDULED
  ],
  [APPOINTMENT_STATUSES.CHECKED_IN]: [APPOINTMENT_STATUSES.CALLED, APPOINTMENT_STATUSES.IN_CONSULTATION],
  [APPOINTMENT_STATUSES.LATE_CHECK_IN]: [APPOINTMENT_STATUSES.CALLED, APPOINTMENT_STATUSES.IN_CONSULTATION],
  [APPOINTMENT_STATUSES.CALLED]: [APPOINTMENT_STATUSES.IN_CONSULTATION],
  [APPOINTMENT_STATUSES.IN_CONSULTATION]: [APPOINTMENT_STATUSES.COMPLETED],
  [APPOINTMENT_STATUSES.COMPLETED]: [],
  [APPOINTMENT_STATUSES.CANCELLED]: [],
  [APPOINTMENT_STATUSES.PATIENT_CANCELLED]: [],
  [APPOINTMENT_STATUSES.CLINIC_CANCELLED]: [],
  [APPOINTMENT_STATUSES.NO_SHOW]: [],
  [APPOINTMENT_STATUSES.RESCHEDULED]: [],
  [APPOINTMENT_STATUSES.PATIENT_RESCHEDULED]: [],
  [APPOINTMENT_STATUSES.CLINIC_RESCHEDULED]: []
};

const DOCTOR_ALLOWED_STATUS_UPDATES = [
  APPOINTMENT_STATUSES.CHECKED_IN,
  APPOINTMENT_STATUSES.LATE_CHECK_IN,
  APPOINTMENT_STATUSES.CALLED,
  APPOINTMENT_STATUSES.IN_CONSULTATION,
  APPOINTMENT_STATUSES.COMPLETED
];

module.exports = {
  APPOINTMENT_STATUSES,
  ACTIVE_APPOINTMENT_STATUSES,
  APPOINTMENT_STATUS_TRANSITIONS,
  DOCTOR_ALLOWED_STATUS_UPDATES
};
