const APPOINTMENT_STATUSES = {
  DRAFT: 'draft',
  PAYMENT_PENDING: 'payment_pending',
  WAIVER_PENDING: 'waiver_pending',
  WAITING_FOR_APPROVAL: 'waiting_for_approval',
  BOOKED: 'booked',
  CONFIRMED: 'confirmed',
  CHECKED_IN: 'checked_in',
  LATE_CHECK_IN: 'late_check_in',
  CALLED: 'called',
  IN_CONSULTATION: 'in_consultation',
  CONSULTATION_STARTED: 'consultation_started',
  CONSULTATION_COMPLETED: 'consultation_completed',
  COMPLETED: 'completed',
  BILLING_PENDING: 'billing_pending',
  PAID: 'paid',
  CLOSED: 'closed',
  CANCELLED: 'cancelled',
  NO_SHOW: 'no_show',
  NOT_ATTENDED: 'not_attended',
  RESCHEDULED: 'rescheduled',
  PATIENT_CANCELLED: 'patient_cancelled',
  CLINIC_CANCELLED: 'clinic_cancelled',
  PATIENT_RESCHEDULED: 'patient_rescheduled',
  CLINIC_RESCHEDULED: 'clinic_rescheduled',
  WAITING: 'waiting',
  RESERVATION_EXPIRED: 'reservation_expired',
  DOCTOR_READY: 'DOCTOR_READY',
  PATIENT_JOINED_WAITING: 'PATIENT_JOINED_WAITING',
  PATIENT_NOTIFIED: 'PATIENT_NOTIFIED',
  PATIENT_JOINED: 'PATIENT_JOINED',
  DOCTOR_JOINED: 'DOCTOR_JOINED',
  VIDEO_CONNECTED: 'VIDEO_CONNECTED',
  CONSULTATION_IN_PROGRESS: 'CONSULTATION_IN_PROGRESS',
  CONSULTATION_COMPLETED: 'CONSULTATION_COMPLETED'
};

const ACTIVE_APPOINTMENT_STATUSES = [
  APPOINTMENT_STATUSES.BOOKED,
  APPOINTMENT_STATUSES.CONFIRMED,
  APPOINTMENT_STATUSES.CHECKED_IN,
  APPOINTMENT_STATUSES.LATE_CHECK_IN,
  APPOINTMENT_STATUSES.CALLED,
  APPOINTMENT_STATUSES.IN_CONSULTATION,
  APPOINTMENT_STATUSES.WAITING,
  APPOINTMENT_STATUSES.CONSULTATION_STARTED,
  APPOINTMENT_STATUSES.DOCTOR_READY,
  APPOINTMENT_STATUSES.PATIENT_JOINED_WAITING,
  APPOINTMENT_STATUSES.PATIENT_NOTIFIED,
  APPOINTMENT_STATUSES.PATIENT_JOINED,
  APPOINTMENT_STATUSES.DOCTOR_JOINED,
  APPOINTMENT_STATUSES.VIDEO_CONNECTED,
  APPOINTMENT_STATUSES.CONSULTATION_IN_PROGRESS
];

const PRE_BOOKING_STATUSES = [
  APPOINTMENT_STATUSES.DRAFT,
  APPOINTMENT_STATUSES.PAYMENT_PENDING,
  APPOINTMENT_STATUSES.WAIVER_PENDING,
  APPOINTMENT_STATUSES.WAITING_FOR_APPROVAL
];

const APPOINTMENT_STATUS_TRANSITIONS = {
  [APPOINTMENT_STATUSES.DRAFT]: [
    APPOINTMENT_STATUSES.PAYMENT_PENDING,
    APPOINTMENT_STATUSES.CANCELLED,
    APPOINTMENT_STATUSES.RESERVATION_EXPIRED
  ],
  [APPOINTMENT_STATUSES.PAYMENT_PENDING]: [
    APPOINTMENT_STATUSES.BOOKED,
    APPOINTMENT_STATUSES.WAITING_FOR_APPROVAL,
    APPOINTMENT_STATUSES.CANCELLED,
    APPOINTMENT_STATUSES.CLINIC_CANCELLED,
    APPOINTMENT_STATUSES.RESERVATION_EXPIRED
  ],
  [APPOINTMENT_STATUSES.WAITING_FOR_APPROVAL]: [
    APPOINTMENT_STATUSES.PAYMENT_PENDING,
    APPOINTMENT_STATUSES.BOOKED,
    APPOINTMENT_STATUSES.CANCELLED,
    APPOINTMENT_STATUSES.CLINIC_CANCELLED,
    APPOINTMENT_STATUSES.RESERVATION_EXPIRED
  ],
  [APPOINTMENT_STATUSES.WAIVER_PENDING]: [
    APPOINTMENT_STATUSES.PAYMENT_PENDING,
    APPOINTMENT_STATUSES.BOOKED,
    APPOINTMENT_STATUSES.CANCELLED,
    APPOINTMENT_STATUSES.CLINIC_CANCELLED,
    APPOINTMENT_STATUSES.RESERVATION_EXPIRED
  ],
  [APPOINTMENT_STATUSES.BOOKED]: [
    APPOINTMENT_STATUSES.CHECKED_IN,
    APPOINTMENT_STATUSES.CONFIRMED,
    APPOINTMENT_STATUSES.CANCELLED,
    APPOINTMENT_STATUSES.PATIENT_CANCELLED,
    APPOINTMENT_STATUSES.CLINIC_CANCELLED,
    APPOINTMENT_STATUSES.NO_SHOW,
    APPOINTMENT_STATUSES.NOT_ATTENDED,
    APPOINTMENT_STATUSES.RESCHEDULED,
    APPOINTMENT_STATUSES.PATIENT_RESCHEDULED,
    APPOINTMENT_STATUSES.CLINIC_RESCHEDULED
  ],
  [APPOINTMENT_STATUSES.CONFIRMED]: [
    APPOINTMENT_STATUSES.CHECKED_IN,
    APPOINTMENT_STATUSES.LATE_CHECK_IN,
    APPOINTMENT_STATUSES.CANCELLED,
    APPOINTMENT_STATUSES.PATIENT_CANCELLED,
    APPOINTMENT_STATUSES.CLINIC_CANCELLED,
    APPOINTMENT_STATUSES.NO_SHOW,
    APPOINTMENT_STATUSES.NOT_ATTENDED,
    APPOINTMENT_STATUSES.RESCHEDULED,
    APPOINTMENT_STATUSES.PATIENT_RESCHEDULED,
    APPOINTMENT_STATUSES.CLINIC_RESCHEDULED
  ],
  [APPOINTMENT_STATUSES.CHECKED_IN]: [
    APPOINTMENT_STATUSES.CALLED,
    APPOINTMENT_STATUSES.IN_CONSULTATION,
    APPOINTMENT_STATUSES.NOT_ATTENDED,
    APPOINTMENT_STATUSES.NO_SHOW,
    APPOINTMENT_STATUSES.WAITING,
    APPOINTMENT_STATUSES.CONSULTATION_STARTED
  ],
  [APPOINTMENT_STATUSES.LATE_CHECK_IN]: [
    APPOINTMENT_STATUSES.CALLED,
    APPOINTMENT_STATUSES.IN_CONSULTATION,
    APPOINTMENT_STATUSES.NOT_ATTENDED,
    APPOINTMENT_STATUSES.NO_SHOW,
    APPOINTMENT_STATUSES.WAITING
  ],
  [APPOINTMENT_STATUSES.CALLED]: [
    APPOINTMENT_STATUSES.IN_CONSULTATION,
    APPOINTMENT_STATUSES.NOT_ATTENDED,
    APPOINTMENT_STATUSES.NO_SHOW,
    APPOINTMENT_STATUSES.CONSULTATION_STARTED
  ],
  [APPOINTMENT_STATUSES.WAITING]: [
    APPOINTMENT_STATUSES.CONSULTATION_STARTED,
    APPOINTMENT_STATUSES.IN_CONSULTATION,
    APPOINTMENT_STATUSES.NO_SHOW,
    APPOINTMENT_STATUSES.NOT_ATTENDED
  ],
  [APPOINTMENT_STATUSES.IN_CONSULTATION]: [
    APPOINTMENT_STATUSES.COMPLETED,
    APPOINTMENT_STATUSES.CONSULTATION_COMPLETED
  ],
  [APPOINTMENT_STATUSES.CONSULTATION_STARTED]: [
    APPOINTMENT_STATUSES.CONSULTATION_COMPLETED,
    APPOINTMENT_STATUSES.COMPLETED
  ],
  [APPOINTMENT_STATUSES.CONSULTATION_COMPLETED]: [
    APPOINTMENT_STATUSES.BILLING_PENDING,
    APPOINTMENT_STATUSES.CLOSED
  ],
  [APPOINTMENT_STATUSES.BILLING_PENDING]: [
    APPOINTMENT_STATUSES.PAID,
    APPOINTMENT_STATUSES.CLOSED
  ],
  [APPOINTMENT_STATUSES.PAID]: [
    APPOINTMENT_STATUSES.CLOSED
  ],
  [APPOINTMENT_STATUSES.COMPLETED]: [
    APPOINTMENT_STATUSES.CLOSED,
    APPOINTMENT_STATUSES.BILLING_PENDING
  ],
  [APPOINTMENT_STATUSES.CANCELLED]: [],
  [APPOINTMENT_STATUSES.PATIENT_CANCELLED]: [],
  [APPOINTMENT_STATUSES.CLINIC_CANCELLED]: [],
  [APPOINTMENT_STATUSES.NO_SHOW]: [
    APPOINTMENT_STATUSES.RESCHEDULED,
    APPOINTMENT_STATUSES.PATIENT_RESCHEDULED,
    APPOINTMENT_STATUSES.CLINIC_RESCHEDULED
  ],
  [APPOINTMENT_STATUSES.NOT_ATTENDED]: [
    APPOINTMENT_STATUSES.RESCHEDULED,
    APPOINTMENT_STATUSES.PATIENT_RESCHEDULED,
    APPOINTMENT_STATUSES.CLINIC_RESCHEDULED
  ],
  [APPOINTMENT_STATUSES.RESCHEDULED]: [],
  [APPOINTMENT_STATUSES.PATIENT_RESCHEDULED]: [],
  [APPOINTMENT_STATUSES.CLINIC_RESCHEDULED]: []
};

const DOCTOR_ALLOWED_STATUS_UPDATES = [
  APPOINTMENT_STATUSES.CHECKED_IN,
  APPOINTMENT_STATUSES.LATE_CHECK_IN,
  APPOINTMENT_STATUSES.CALLED,
  APPOINTMENT_STATUSES.IN_CONSULTATION,
  APPOINTMENT_STATUSES.COMPLETED
];

const APPOINTMENT_STATUS_LABELS = {
  draft: 'Draft',
  payment_pending: 'Payment Pending',
  waiver_pending: 'Waiver Pending',
  waiting_for_approval: 'Awaiting Approval',
  booked: 'Booked Successfully',
  confirmed: 'Confirmed',
  checked_in: 'Checked In',
  late_check_in: 'Late Check-In',
  called: 'Called',
  in_consultation: 'In Consultation',
  consultation_started: 'Consultation Started',
  consultation_completed: 'Consultation Completed',
  completed: 'Completed',
  billing_pending: 'Billing Pending',
  paid: 'Paid',
  closed: 'Closed',
  cancelled: 'Cancelled',
  patient_cancelled: 'Cancelled by Patient',
  clinic_cancelled: 'Cancelled by Clinic',
  no_show: 'No Show',
  not_attended: 'Not Attended',
  rescheduled: 'Rescheduled',
  patient_rescheduled: 'Rescheduled by Patient',
  clinic_rescheduled: 'Rescheduled by Clinic',
  waiting: 'Waiting',
  reservation_expired: 'Reservation Expired'
};

module.exports = {
  APPOINTMENT_STATUSES,
  ACTIVE_APPOINTMENT_STATUSES,
  PRE_BOOKING_STATUSES,
  APPOINTMENT_STATUS_TRANSITIONS,
  APPOINTMENT_STATUS_LABELS,
  DOCTOR_ALLOWED_STATUS_UPDATES
};
