const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  DOCTOR: 'DOCTOR',
  RECEPTIONIST: 'RECEPTIONIST',
  PHARMACIST: 'PHARMACIST',
  LAB_TECHNICIAN: 'LAB_TECHNICIAN',
  NURSE: 'NURSE',
  ACCOUNTANT: 'ACCOUNTANT',
  CLINIC_MANAGER: 'CLINIC_MANAGER',
  PATIENT: 'PATIENT',
  AI_ADMIN: 'AI_ADMIN',
  PHARMACY_OPERATOR: 'Pharmacy Store Operator',
  LAB_OPERATOR: 'Laboratory Operator',
  IMAGING_OPERATOR: 'Imaging Operator',
  PHYSIOTHERAPY_OPERATOR: 'Physiotherapy Operator',
  AMBULANCE_COORDINATOR: 'Ambulance Coordinator',
  HOME_CARE_OPERATOR: 'Home Care Operator'
};

const PUBLIC_REGISTRATION_ROLES = [
  ROLES.PATIENT,
  ROLES.RECEPTIONIST,
  ROLES.DOCTOR,
  ROLES.PHARMACIST,
  ROLES.LAB_TECHNICIAN,
  ROLES.NURSE,
  ROLES.ACCOUNTANT,
  ROLES.CLINIC_MANAGER
];

const ADMIN_ROLES = [ROLES.SUPER_ADMIN, ROLES.ADMIN];

const STAFF_ROLES = [
  ROLES.RECEPTIONIST,
  ROLES.PHARMACIST,
  ROLES.LAB_TECHNICIAN,
  ROLES.NURSE,
  ROLES.ACCOUNTANT,
  ROLES.CLINIC_MANAGER,
  ROLES.PHARMACY_OPERATOR,
  ROLES.LAB_OPERATOR,
  ROLES.IMAGING_OPERATOR,
  ROLES.PHYSIOTHERAPY_OPERATOR,
  ROLES.AMBULANCE_COORDINATOR,
  ROLES.HOME_CARE_OPERATOR
];

module.exports = {
  ROLES,
  PUBLIC_REGISTRATION_ROLES,
  ADMIN_ROLES,
  STAFF_ROLES
};
