const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  DOCTOR: 'DOCTOR',
  RECEPTIONIST: 'RECEPTIONIST',
  PHARMACIST: 'PHARMACIST',
  LAB_TECHNICIAN: 'LAB_TECHNICIAN',
  PATIENT: 'PATIENT',
  AI_ADMIN: 'AI_ADMIN'
};

const PUBLIC_REGISTRATION_ROLES = [
  ROLES.PATIENT,
  ROLES.RECEPTIONIST,
  ROLES.DOCTOR,
  ROLES.PHARMACIST,
  ROLES.LAB_TECHNICIAN
];

const ADMIN_ROLES = [ROLES.SUPER_ADMIN, ROLES.ADMIN];

module.exports = {
  ROLES,
  PUBLIC_REGISTRATION_ROLES,
  ADMIN_ROLES
};
