const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  DOCTOR: 'DOCTOR',
  RECEPTIONIST: 'RECEPTIONIST',
  PHARMACIST: 'PHARMACIST',
  LAB_TECHNICIAN: 'LAB_TECHNICIAN',
  NURSE: 'NURSE',
  ACCOUNTANT: 'ACCOUNTANT',
  CLINIC_MANAGER: 'CLINIC_MANAGER',
  PATIENT: 'PATIENT',
  AI_ADMIN: 'AI_ADMIN'
};

const PUBLIC_REGISTRATION_ROLES = [
  ROLES.PATIENT,
  ROLES.RECEPTIONIST,
  ROLES.DOCTOR,
  ROLES.PHARMACIST,
  ROLES.LAB_TECHNICIAN,
  ROLES.NURSE,
  ROLES.ACCOUNTANT,
  ROLES.CLINIC_MANAGER
];

const ADMIN_ROLES = [ROLES.SUPER_ADMIN, ROLES.ADMIN];

const STAFF_ROLES = [
  ROLES.RECEPTIONIST,
  ROLES.PHARMACIST,
  ROLES.LAB_TECHNICIAN,
  ROLES.NURSE,
  ROLES.ACCOUNTANT,
  ROLES.CLINIC_MANAGER
];

module.exports = {
  ROLES,
  PUBLIC_REGISTRATION_ROLES,
  ADMIN_ROLES,
  STAFF_ROLES
};
