export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  RECEPTIONIST: 'RECEPTIONIST',
  DOCTOR: 'DOCTOR',
  PHARMACIST: 'PHARMACIST',
  LAB_TECHNICIAN: 'LAB_TECHNICIAN',
  NURSE: 'NURSE',
  ACCOUNTANT: 'ACCOUNTANT',
  CLINIC_MANAGER: 'CLINIC_MANAGER',
  PATIENT: 'PATIENT',
  PHARMACY_OPERATOR: 'Pharmacy Store Operator',
  LAB_OPERATOR: 'Laboratory Operator',
  IMAGING_OPERATOR: 'Imaging Operator',
  PHYSIOTHERAPY_OPERATOR: 'Physiotherapy Operator',
  AMBULANCE_COORDINATOR: 'Ambulance Coordinator',
  HOME_CARE_OPERATOR: 'Home Care Operator'
};

export const ADMIN_ROLES = [ROLES.SUPER_ADMIN, ROLES.ADMIN];

export const STAFF_ROLES = [
  ROLES.RECEPTIONIST,
  ROLES.PHARMACIST,
  ROLES.LAB_TECHNICIAN,
  ROLES.NURSE,
  ROLES.ACCOUNTANT,
  ROLES.CLINIC_MANAGER,
  ROLES.PHARMACY_OPERATOR,
  ROLES.LAB_OPERATOR,
  ROLES.IMAGING_OPERATOR,
  ROLES.PHYSIOTHERAPY_OPERATOR,
  ROLES.AMBULANCE_COORDINATOR,
  ROLES.HOME_CARE_OPERATOR
];

export const canAccessRole = (role, allowedRoles = []) => {
  if (!allowedRoles.length) {
    return true;
  }

  if (!role) {
    return false;
  }

  return allowedRoles.includes(role);
};
